settings:
- ArrowParticles
- AttackSpeedometer
- Blood
- DamageNumbers
- DeathMessages
- Elytra
- Health
- HighlightDeathMessages
- JoinMessages
- Observers
- Picker
- PrivateMessages
- PrivateMessageSounds
- Scoreboard
- Snowflakes
- Sounds
- Speed
- Stats
setting:
  ArrowParticles:
    aliases:
    - arrows
    values:
    - 'all'
    - self[default]
    - 'none'
    description: Show team colored particles with arrows
  AttackSpeedometer:
    aliases:
    - cps
    values:
    - 'on'
    - off[default]
    description: Show attack speed information
  Blood:
    values:
    - 'on'
    - off[default]
    description: See blood when players get hurt
  DamageNumbers:
    aliases:
    - damage
    values:
    - on[default]
    - 'off'
    description: Show floating damage numbers
  DeathMessages:
    aliases:
    - dms
    values:
    - own
    - all[default]
    description: Death messages displayed to you
  Elytra:
    values:
    - 'on'
    - off[default]
    description: Equips you with elytra when you are in observer mode
  Health:
    values:
    - 'long'
    - short[default]
    - 'tiny'
    - 'off'
    description: See health of joined players when you are in observer mode
  HighlightDeathMessages:
    aliases:
    - hdms
    values:
    - underline
    - italics
    - white
    - none
    - bold[default]
    description: Highlight death messages that you are involved in
  JoinMessages:
    aliases:
    - jms
    values:
    - none
    - all[default]
    description: Join messages displayed to you
  Observers:
    aliases:
    - obs
    values:
    - none
    - all[default]
    description: See other observers while spectating
  Picker:
    values:
    - 'off'
    - on[default]
    description: Open a helpful GUI for picking classes and teams
  PrivateMessages:
    aliases:
    - pmr
    values:
    - none
    - all[default]
    description: Who can send you private messages
  PrivateMessageSounds:
    aliases:
    - pms
    values:
    - 'off'
    - on[default]
    description: Hear sounds when a private message is sent to you
  Scoreboard:
    values:
    - 'off'
    - on[default]
    description: See the scoreboard with game information
  Snowflakes:
    values:
    - 'off'
    - on[default]
    description: See snowflakes visual effects
  Sounds:
    values:
    - 'off'
    - on[default]
    description: Hear sounds to alert you of the last three seconds of a countdown
  Speed:
    values:
    - 1.0[default]
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    description: Change speed while on observers
  Stats:
    aliases:
    - kd
    values:
    - 'sidebar'
    - 'action bar'
    - 'boss bar'
    - off[default]
    description: See your Kills, Deaths and kd stats