settings:
- AttackSpeedometer
- Blood
- DamageNumbers
- DeathMessages
- HighlightDeathMessages
- JoinMessages
- Observers
- Picker
- PrivateMessages
- PrivateMessageSounds
- Scoreboard
- Sounds
- Stats
setting:
  AttackSpeedometer:
    aliases:
    - cps
    values:
    - 'on'
    - off[default]
    description: Show attack speed information
  Blood:
    values:
    - 'on'
    - off[default]
    description: See blood when players get hurt
  DamageNumbers:
    aliases:
    - damage
    values:
    - on[default]
    - 'off'
    description: Show floating damage numbers
  DeathMessages:
    aliases:
    - dms
    values:
    - own
    - all[default]
    description: Death messages displayed to you
  HighlightDeathMessages:
    aliases:
    - hdms
    values:
    - underline
    - italics
    - white
    - none
    - bold[default]
    description: Highlight death messages that you are involved in
  JoinMessages:
    aliases:
    - jms
    values:
    - none
    - all[default]
    description: Join messages displayed to you
  Observers:
    aliases:
    - obs
    values:
    - none
    - all[default]
    description: See other observers while spectating
  Picker:
    values:
    - 'off'
    - on[default]
    description: Open a helpful GUI for picking classes and teams
  PrivateMessages:
    aliases:
    - pmr
    values:
    - none
    - all[default]
    description: Who can send you private messages
  PrivateMessageSounds:
    aliases:
    - pms
    values:
    - 'off'
    - on[default]
    description: Hear sounds when a private message is sent to you
  Scoreboard:
    values:
    - 'off'
    - on[default]
    description: See the scoreboard with game information
  Sounds:
    values:
    - 'off'
    - on[default]
    description: Hear sounds to alert you of the last three seconds of a countdown
  Stats:
    values:
    - 'off'
    - on[default]
    description: See your statistics at the end of the game